### ISSUE TITLE
Does not work with KiCad 7

### ISSUE THREAD

**Issue by cobra18t** [tristanitschner/kicad_spiral_plugin#1]
Is this supposed to work with KiCad 7? I am getting this when I start the plugin:

![image](https://user-images.githubusercontent.com/1877729/235285452-8923c32f-4abd-405c-b6e0-0a39f12a6e1a.png)

**Comment by tristanitschner** [comment]
I just took a quick look. It seems like they dropped the BOARD_ prefix in the newest version.  Mangling in naming from one version to the next is a common theme with KiCAD's python API. If you encounter further similar issues, please refer to the autogenerated SWIG python API which allows for calling KiCADs C++ code directly and contains all the defines that may have changed.

When I wrote this plugin, KiCAD 6 just came out, so supporting version 7 was actually never on my mind. Of course if you'd manage to get it working on version 7 (shouldn't be too hard), you can do a pull request.

**Comment by tristanitschner** [comment]
So I tested again with version 6.0 and can confirm that the plugin is working. 

However, I cannot test on the newest version 7.99 due to this bug:
https://gitlab.com/kicad/code/kicad/-/issues/14266
Unfortunately it does not seem custom Linux builds be supported in the future.

I would advise you to use KiCAD version 6.0.

**Comment by tristanitschner** [comment]
I couldn't help myself, got the newest KiCAD version 7.99 working and fixed the plugin.

Could you test whether it works on version 7.0 too?
